# Generated by Django 5.0.7 on 2024-07-10 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=100, verbose_name='Марка автомобиля')),
                ('car_model', models.TextField(max_length=100, verbose_name='Модель автомобиля')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата добавления записи')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('code', models.CharField(max_length=10, verbose_name='Код страны')),
                ('currency', models.CharField(max_length=50, verbose_name='Валюта')),
            ],
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('autos', models.ManyToManyField(to='auto.auto', verbose_name='Подходит для автомобилей')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.country', verbose_name='Страна производства')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.country', verbose_name='Страна производства'),
        ),
    ]
