# Generated by Django 5.0.7 on 2024-07-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_auto_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, verbose_name='Название страны')),
            ],
        ),
        migrations.AlterField(
            model_name='auto',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.country'),
        ),
    ]
