# Generated by Django 5.0.7 on 2024-07-09 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_carparts_country_alter_auto_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarParts',
            new_name='CarPart',
        ),
        migrations.AlterField(
            model_name='auto',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.country', verbose_name='Страна производства'),
        ),
    ]
