# Generated by Django 5.0.7 on 2024-07-09 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_rename_carparts_carpart_alter_auto_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='price',
            field=models.IntegerField(default=10, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='carpart',
            name='autos',
            field=models.ManyToManyField(to='auto.auto', verbose_name='Подходит для автомобилей'),
        ),
        migrations.AddField(
            model_name='carpart',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto.country', verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='RUS', max_length=10, verbose_name='Код страны'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='рубль', max_length=50, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto.country', verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Цена'),
        ),
    ]
